In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.6'

In [3]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

In [4]:
df = pd.read_csv(url)

In [5]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [6]:
df.shape

(10000, 11)

In [7]:
len(df)

10000

In [8]:
df["fuel_type"].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [9]:
df["fuel_type"].nunique()

3

In [10]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [11]:
df.isna().sum() > 0

model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors              False
engine_displacement    False
num_cylinders          False
horsepower              True
vehicle_weight         False
acceleration            True
fuel_efficiency_mpg    False
dtype: bool

In [12]:
(df.isna().sum() > 0).sum()

np.int64(2)

In [13]:
df["origin"] == "Asia"

0       False
1       False
2        True
3       False
4       False
        ...
9995    False
9996     True
9997    False
9998    False
9999    False
Name: origin, Length: 10000, dtype: bool

In [14]:
asia = df[df["origin"] == "Asia"]

In [15]:
asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [16]:
asia["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [17]:
median_before = df["horsepower"].median()
median_before

np.float64(254.0)

In [18]:
df["horsepower"].mode()

0    252.0
Name: horsepower, dtype: float64

In [19]:
most_frequent = df["horsepower"].mode()[0]
most_frequent

np.float64(252.0)

In [20]:
horsepower_filled = df["horsepower"].fillna(most_frequent)

In [21]:
median_after = horsepower_filled.median()
median_after

np.float64(252.0)

In [22]:
median_before, median_after

(np.float64(254.0), np.float64(252.0))

In [23]:
X = (
    df[df["origin"] == "Asia"]
    [["vehicle_weight", "model_year"]]
    .head(7)
    .to_numpy()
)

In [24]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [25]:
X.shape

(7, 2)

In [26]:
X.T

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [27]:
X.T.shape

(2, 7)

In [28]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [29]:
XTX.shape

(2, 2)

In [30]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [31]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [32]:
w = XTX_inv @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [33]:
w.sum()

np.float64(0.36919696904925486)